version: '3.3'

services:
  db:
    container_name: mysql_server
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - d:/CodingProjects/Python/orders_generator/env/sql:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    networks:
      localnet:
        ipv4_address: 172.16.238.2

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.7.14-management-alpine"
    ports:
      - "15673:15672"
      - "5673:5672"
    networks:
      localnet:
        ipv4_address: 172.16.238.3

  app:
    container_name: generator_app
    image: "order_gen"
    ports:
      - "5000:5000"
    networks:
      localnet:
        ipv4_address: 172.16.238.4
    links:
      - rabbitmq
      - db

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
