version: '3.3'

services:
  db:
    image: mysql:8.0
    hostname: 'mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'test'
    ports:
      - '3306:3306'
    networks:
      - localnet

  rabbitmq:
    image: "rabbitmq:3.7.14-management-alpine"
    hostname: 'rabbit'
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - localnet

networks:
  localnet:
    external:
      name: localnet