class ConstKeys:
    id_length = "id_length"
    default_length = "default_length"
    x_default = "x_default"
    y_default = "y_default"
    a_default = "a_default"
    c_default = "c_default"
    m_default = "m_default"
    t0_default = "t0_default"
    zones = "zones"
    direction = "direction"
    statuses = "statuses"
    descriptions = "descriptions"
    tags = "tags"
