class ReportDataKeys:
    red = "red"
    green = "green"
    blue = "blue"
    amount = "amount"
    avg = "avg"
    sum = "sum"
    min = "min"
    max = "max"
    rabbit_consumed = "rabbit_consumed"
    mysql_new = "mysql_new"
    mysql_to_provider = "mysql_to_provider"
    mysql_rejected = "mysql_rejected"
    mysql_partial_filled = "mysql_partial_filled"
    mysql_filled = "mysql_filled"
