class PathKeys:
    ROOT = "ROOT",
    LOG = "LOG",
    SETTINGS = "SETTINGS",
    CONSTANTS = "CONSTANTS",
    DEFAULT_SETTINGS = "DEFAULT_SETTINGS",
    DEFAULT_CONSTANTS = "DEFAULT_CONSTANTS",
    GEN_OUT = "GEN_OUT"
